# Generated by Django 4.2.29 on 2026-03-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats_python_api', '0001_generate_cats_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='api_used',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
